server:
    port: 8000

    prod:
        url: ${PROD_BASE_URL}

spring:
    application:
        name: code-solution-app

    devtools:
        livereload:
            enabled: true
    datasource:
        url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}?currentSchema=${PROD_SCHEMA_NAME}
        username: ${PROD_DB_USER}
        password: ${PROD_DB_PASSWORD}
        driverClassName: org.postgresql.Driver
    sql:
        init:
            mode: always
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        open-in-view: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
    file:
        name: mylog.log
    level:
        root: info

frontend:
    url: ${PROD_FRONTEND_URL}
    mobile:
        url: ${PROD_FRONTEND_MOBILE_URL}

folder:
    url: ${CODE_FOLDER_PATH}

third-party:
    sending-email:
        address: ${PRO_EMAIL_ADDRESS}
        password: ${PRO_EMAIL_PASSWORD}

    paypal:
        clientId: ${PRO_PAYPAL_CLIENT_ID}
        clientSecret: ${PRO_PAYPAL_CLIENT_SECRET}
        mode: ${PRO_PAYPAL_MODE}
        returnUrl: ${PRO_PAYPAL_RETURN_URL}
        cancelUrl: ${PRO_PAYPAL_CANCEL_URL}