server:
    port: 8000

    prod:
        url: ${PROD_BASE_URL}

spring:
    application:
        name: code-solution-app

    devtools:
        livereload:
            enabled: true

    # MongoDB Configuration
    data:
        mongodb:
            uri: mongodb://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
            database: ${PROD_DB_NAME}
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Logging Configuration
logging:
    file:
        name: mylog.log
    level:
        root: info

frontend:
    url: ${PROD_FRONTEND_URL}
    mobile:
        url: ${PROD_FRONTEND_MOBILE_URL}

folder:
    url: ${CODE_FOLDER_PATH}

third-party:
    sending-email:
        address: ${PRO_EMAIL_ADDRESS}
        password: ${PRO_EMAIL_PASSWORD}

    paypal:
        clientId: ${PRO_PAYPAL_CLIENT_ID}
        clientSecret: ${PRO_PAYPAL_CLIENT_SECRET}
        mode: ${PRO_PAYPAL_MODE}
        returnUrl: ${PRO_PAYPAL_RETURN_URL}
        cancelUrl: ${PRO_PAYPAL_CANCEL_URL}
